### ISSUE TITLE
configurations never change

### ISSUE THREAD

**Issue by Chaiavi** [sairuk/pyANS#12]
Configurations never change, even when I edit them, they remain with the initial values

This is a design call, as I understand you chose to copy the settings to the user's home folder then use it from there.
I think this is a mistake, as a user (like me) updates the config.example I have near the pyans.py file and I don't understand why the values remain the same (because they are taken now from the home folder).

IMHO configurations should always be taken from the config.example file or any other file but it should be consistent

**Comment by sairuk** [comment]
Thanks for your feedback.

You do need to edit the correct file for the settings to change.

config.example is an example only, this is already documented in the readme

this is by design and wont be changing.
