### ISSUE TITLE
Exception is thrown when reading zip archives

### ISSUE THREAD

**Issue by Chaiavi** [sairuk/pyANS#13]
I downloaded 3 random zip files from sixteencolors (official ANSI archive)

But an exception is thrown :-( 
  File "/usr/lib/python3.9/zipfile.py", line 678, in _check_compression
    raise NotImplementedError("That compression method is not supported")
NotImplementedError: That compression method is not supported

Zip files I tried are:
acdu1092.zip
acid-77a.zip
cph.artpack29.zip

They do open on my Raspbian OS when I click them on my desktop

**Comment by sairuk** [comment]
hrrrm, thanks for reporting this.

cph.artpack29 is using deflate compression method. I'll need to add code to handle these

**Comment by sairuk** [comment]
I just tested this, the `cph.artpack29` pack runs fine here. `Zipfile` will handle deflate etc providing `zlib` is available 

| Pack | Method |
|--------|-----------|
|cph.artpack29.zip|deflate|
|acdu1092.zip|Imploding|
|acid-77a.zip |deflate|

`acdu1092` with `Imploding` compression throws this NotImplementedError for, I will use that as a basis and see what I can do for replicating it with `deflate`. I will perhaps need to look at defining a `requirements.txt` so you can install the appropriate modules if you don't have them. I will look into the feasibility of that.

**Comment by sairuk** [comment]
Have scanned the entire 16c tree and found these methods

|Method|
|-|
|deflate|
|Imploding|
|Shrinking|
|store|

I will need to see about support for Imploding/Shrinking

For now I am working on skipping problem archives, so the scroller continues to run

**Comment by sairuk** [comment]
The core python zipfile module does not support the old style Imploding/Shrinking compression so we cannot support these at the moment. I tried some modules that were said to support Imploding compression to no avail.

As a workaround these packs can be repacked to deflate/store compression to be compatible with pyANS. 

I have scanned the entire 16c archive and checked how widespread Imploding/Shrinking use was, readme has been updated

for reference, you would need to convert 52 out of 4474 packs, a report of these packs is available [here](https://github.com/sairuk/pyANS/blob/master/pack_info/unsupported.md) 
```
      1 
   3454 deflate
     49 Imploding
      3 Shrinking
    967 store
```

If anyone wants to do the work and provide a pull request to support Imploding/Shrinking it would be better do it against the core zipfile module than here.

pyANS should now skip problem packs by adding them to a runtime blacklist when encountered.

**Comment by Chaiavi** [comment]
@sairuk Amazing work you did here.

I think this issue can be closed now after your latest commits.

To sum it up:
Some original art-packs (only 42 out of more than 3000) are using an ancient algorithm of Zip which is not supported by the official zip module in python (and several others).

So now pyAns will identify those and skip them using a blacklist (Maybe a try/catch will catch also other bad art packages ?).

And now all Sixteen-colors art-packs can be downloaded (The whole project with all of the packs can be cloned and copied to the ansi-store folder), and you have added a script to convert those badly packaged zip files to a readble-by-pyans format.


Thank you.

**Comment by Chaiavi** [comment]
Opened an issue in 16c, hopefully they will agree to convert them to a more modern zip packaging

**Comment by sairuk** [comment]
I will close this issue thanks.
