### ISSUE TITLE
TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by k0bura** [sairuk/pyANS#6]
If there is a problem reading a pack, script exits with the below error. I fixed it by setting ansi on ine 85 to an empty array: ansi = []. This at least keep the script going.

![image](https://cloud.githubusercontent.com/assets/2078178/13690276/21d02bda-e6fd-11e5-95ec-82222d7cf750.png)

**Comment by sairuk** [comment]
This is bug from last commit, corrected now
