### ISSUE TITLE
Android Qpython pyANS Decode Error

### ISSUE THREAD

**Issue by convolutionbbs** [sairuk/pyANS#9]
Hello,
I have an old Android tablet I'd like to make in to a pyANS scroller.  I installed QPython and got the basic pyANS script to work.

When the script gets to the actual write code:

writeout(char.decode(cp))

I get:

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2580' in position 0: ordinal not in range(128).

The character changes depending on which random file it tries (ex: u'\u2584').  

I tried changing to:
writeout(char.decode(cp).encode('utf-8'))

This actually displays color text / blocks, but they are all out of order / not showing correctly.

I haven't dived in to any of the encoding options in python, nor am I much of a developer.  Does anyone know what I could try to get the ansi files to decode properly?

Thanks!

**Comment by sairuk** [comment]
sorry, i didn't see this at all back in 2017, I am not familiar with the version of python qpython was based on back then, so i'm not sure what can be done about. If i can get one of these old android tablets running i have here I'll see if i can take a look at it

**Comment by sairuk** [comment]
Assume you've moved on from this based on the time. I did take a look at this but I don't have a device that will run the new qpython on android unfortunately.

If you come back to this, try again with the python3 version.
